version: '{build}'
image: Visual Studio 2017
environment:
  USE_S3: false
build_script:
- ps: >-
    mkdir build

    cd build

    $env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin"

    ..\scripts\install-deps.ps1

    if ($env:USE_S3 -eq "true") {
      ..\scripts\install-s3.ps1
      ..\scripts\install-minio.ps1
      ..\bootstrap.ps1 -S3 -EnableVerbose
    } else {
      ..\bootstrap.ps1 -EnableVerbose
    }
test_script:
- ps: cmake --build . --target check --config Release
