sudo: required
dist: trusty
language: cpp
env:
    matrix:
        - USE_MPI="ON"
        - USE_MPI="OFF"

install:
    # Install library dependencies
    - sudo scripts/install-deps.sh
    # Install clangformat (v5.0)
    # - sudo scripts/install-clangformat.sh
    # Install lcov to coveralls conversion + upload tool
    - gem install coveralls-lcov
    # Build TileDB
    - mkdir -p $TRAVIS_BUILD_DIR/build
    - cd $TRAVIS_BUILD_DIR/build
    - cmake -DCMAKE_BUILD_TYPE=Coverage  -DTILEDB_VERBOSE=1 -DUSE_MPI=$USE_MPI ..
    - make -j4
    - make examples -j4
    
before_script:
    - lcov --directory $TRAVIS_BUILD_DIR/build --zerocounters

script:
    # - make check-format
    - make check

after_success:
    - cd $TILEDB_BUILD_DIR/build
    - lcov --directory . --capture --output-file coverage.info
    - lcov --list coverage.info # debug before upload
