# Adapted from 
# http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/

sudo: required
dist: trusty

env:
    - TILEDB_BUILD_DIR=$TRAVIS_BUILD_DIR/build

install:
    # Install cmake, lcov, MPICH
    - sudo apt-get -y install cmake lcov mpich
    # Install zlib, bzip2 and LZ4
    - sudo apt-get -y install zlib1g-dev libbz2-dev liblz4-dev
    # Install OpenSSL
    - sudo apt-get -y install libssl-dev
    # Install Zstandard
    - wget https://github.com/facebook/zstd/archive/v1.0.0.tar.gz
    - tar xf v1.0.0.tar.gz
    - cd zstd-1.0.0
    - sudo make install PREFIX='/usr'
    - cd $TRAVIS_BUILD_DIR
    # Install Blosc
    - git clone https://github.com/Blosc/c-blosc 
    - cd c-blosc
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX='/usr' ..
    - cmake --build .
    - sudo cmake --build . --target install
    - cd $TRAVIS_BUILD_DIR
    # Install lcov to coveralls conversion + upload tool
    - gem install coveralls-lcov
    # Install clang-format
    - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo apt-get update -qq 
    - sudo apt-get install -qq -y clang-format-5.0
    # Build TileDB
    - rm -rf $TILEDB_BUILD_DIR
    - mkdir -p $TILEDB_BUILD_DIR
    - cd $TILEDB_BUILD_DIR
    - cmake .. -DCMAKE_BUILD_TYPE=Coverage 
    - make -j4
    - make examples -j4
    
before_script:
    - lcov --directory $TILEDB_BUILD_DIR --zerocounters

script:
    - make check-format
    - make check

after_success:
    - cd $TILEDB_BUILD_DIR
    - lcov --directory . --capture --output-file coverage.info
    - lcov --list coverage.info # debug before upload
