language: cpp

dist: trusty
sudo: required
services: docker

matrix:
  include:
    - os: linux

    - os: linux
      env: USE_HDFS="ON"

    - os: linux
      env: USE_S3="ON"

    - os: osx

install:
    # Install clangformat (v5.0)
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo scripts/install-clangformat.sh;
      else
        scripts/install-clangformat.sh;
      fi

    # Set up arguments for install-deps.sh and bootstrap.
    - deps_args="";
      bootstrap_args="--enable=coverage,verbose";
      if [[ "$USE_HDFS" == "ON" ]]; then
        deps_args="${deps_args} --enable-hdfs";
        bootstrap_args="${bootstrap_args} --enable-hdfs";
      fi;
      if [[ "$USE_S3" == "ON" ]]; then
        deps_args="${deps_args} --enable-s3";
        bootstrap_args="${bootstrap_args} --enable-s3";
      fi

    # Install library dependencies
    - scripts/install-deps.sh $deps_args

    # Start HDFS server if enabled
    - if [[ "$USE_HDFS" == "ON" ]]; then
        source scripts/run-hadoop.sh;
      fi

    # Start minio server if S3 is enabled
    - if [[ "$USE_S3" == "ON" ]]; then
        source scripts/run-minio.sh;
      fi

    - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build

    # Configure and build TileDB
    - ../bootstrap $bootstrap_args

    - make -j4
    - make examples -j4
    
script:
    - make check-format
    - make check
