# Adapted from 
# http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/

sudo: required
dist: trusty

env:
    - TILEDB_BUILD_DIR=$TRAVIS_BUILD_DIR/build

install:
    - sudo scripts/install-travis-deps.sh

    # Install lcov to coveralls conversion + upload tool
    - gem install coveralls-lcov

    # Build TileDB
    - cd $TRAVIS_BUILD_DIR
    - rm -rf $TILEDB_BUILD_DIR
    - mkdir -p $TILEDB_BUILD_DIR
    - cd $TILEDB_BUILD_DIR
    - cmake -DCMAKE_BUILD_TYPE=Coverage  -DTILEDB_VERBOSE=1 ..
    - make -j4
    - make examples -j4
    
before_script:
    - lcov --directory $TILEDB_BUILD_DIR --zerocounters

script:
    - make check-format
    - make check

after_success:
    - cd $TILEDB_BUILD_DIR
    - lcov --directory . --capture --output-file coverage.info
    - lcov --list coverage.info # debug before upload
